include:
  - docker-compose.tools.yml
services:
  algashop-product-catalog:
    image: algashop/product-catalog:dev
    restart: no
    ports:
      - 8083:8083
    depends_on:
      algashop-mongodb-1:
        condition: service_healthy
      algashop-redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      SPRING_PROFILES_ACTIVE: docker
  algashop-ordering:
    image: algashop/ordering:dev
    restart: no
    ports:
      - 8080:8080
    depends_on:
      algashop-postgres:
        condition: service_healthy
      algashop-redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_TOMCAT_THREADS_MAX: 10
      SPRING_THREADPOOL_VIRTUAL_THREADS_ENABLED: true
  algashop-billing:
    image: algashop/billing:dev
    restart: no
    ports:
      - 8082:8082
    depends_on:
      algashop-postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      SPRING_PROFILES_ACTIVE: docker
