spring:
  config:
    import:
      - aws-secretsmanager:/secret/algashop/product-catalog/redis?prefix=product-catalog.secrets.redis.
      - aws-parameterstore:/config/algashop/product-catalog?prefix=product-catalog.params
  cache:
    type: redis
  mongodb:
    uri: ${product-catalog.params.mongodb.uri}
  data:
    redis:
      host: ${product-catalog.params.redis.host}
      port: ${product-catalog.params.redis.port}
      password: ${product-catalog.secrets.redis.password}
      database: ${product-catalog.params.redis.database}
      timeout: ${product-catalog.params.redis.timeout}
  cloud:
    aws:
      region:
        static: us-east-1
      endpoint: http://algashop-localstack:4566
      credentials:
        access-key: test
        secret-key: test
      s3:
        enabled: true
        path-style-access-enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${product-catalog.params.integrations.authorization-server.url}

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.cluster: OFF

algashop:
  data-load:
    enabled: true
    auto-delete: true
  mapping:
    image-storage-url: ${product-catalog.params.mapping.image-storage-url}
  storage:
    s3:
      bucket-name: ${product-catalog.params.s3.bucket-name}
